project_id = "wqgotyhepamnwsjcydpy"

[functions.giphy-proxy]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.export-user-data]
verify_jwt = false

[functions.resolve-device-location]
verify_jwt = false

[functions.create-streampay-checkout]
verify_jwt = false

[functions.streampay-webhook]
verify_jwt = false

[functions.create-pro-checkout]
verify_jwt = false

[functions.cancel-streampay-subscription]
verify_jwt = false

[functions.cancel-pro-subscription]
verify_jwt = false

[functions.generate-transcript]
verify_jwt = false
